/**
 * @file main.c
 * @brief nRF51 flash dumper — streams the dashboard's flash out over the Ninebot bus.
 *
 * Port of the deleted STM32 `firmware/bootloader-dumper` (which targeted a dashboard STM32 that
 * does not exist — see boards/ble-dashboard/MCU_IDENTIFICATION.md). This version runs on the
 * dashboard's actual MCU, from the application slot at 0x00018000.
 *
 * It is **read-only**: it never erases or programs anything, so it cannot brick the board.
 *
 * ## What it can and cannot read
 *
 * The MPU decides, based on `UICR.RBPCONF.PR0` (nRF51 RM ch. 9):
 *
 *   *"When enabled, only code running from code region 0 will be able to access the code in code
 *    region 0. Accesses generated by code running from code region 1 or from RAM, as well as
 *    accesses generated by the debugger (SWD), will not be granted."*
 *
 * This app runs in **code region 1**, so:
 *   - PR0 clear  -> the whole 256 KB, SoftDevice included, is readable.
 *   - PR0 set    -> region 0 (0x0 .. UICR.CLENR0) is NOT readable, and touching it would
 *                   *hard fault* (*"accesses that are not granted by the MPU will result in a
 *                   hard fault"*). We therefore probe PR0 first and skip that range, reporting it
 *                   as protected instead of crashing.
 *   - The vector table at 0x0..0x80 is never protected, so it is always dumped.
 *
 * ⚠️ Installing this app **overwrites the stock application**. Dump over SWD first
 * (tools/nrf51/nrf51_swd.py) if you want the stock app preserved — SWD needs no app slot at all.
 *
 * Wire protocol: Ninebot `5A A5` frames, SRC 0x21 (dashboard) -> DST 0x3F (PC), 115200 8N1
 * half-duplex on P0.15/P0.20. See tools/nrf51/nrf51_dump_receive.py.
 */

#include <stdint.h>
#include <stddef.h>

/* ── nRF51 registers (only what this app needs) ───────────────────────────── */
#define REG(a)                  (*(volatile uint32_t *)(a))

#define GPIO_BASE               0x50000000UL
#define GPIO_PIN_CNF(n)         REG(GPIO_BASE + 0x700UL + 4UL * (n))
#define UART0_BASE              0x40002000UL
#define UART_TASKS_STARTRX      REG(UART0_BASE + 0x000)
#define UART_TASKS_STARTTX      REG(UART0_BASE + 0x008)
#define UART_EVENTS_RXDRDY      REG(UART0_BASE + 0x108)
#define UART_EVENTS_TXDRDY      REG(UART0_BASE + 0x11C)
#define UART_ENABLE             REG(UART0_BASE + 0x500)
#define UART_PSELTXD            REG(UART0_BASE + 0x50C)
#define UART_PSELRXD            REG(UART0_BASE + 0x514)
#define UART_RXD                REG(UART0_BASE + 0x518)
#define UART_TXD                REG(UART0_BASE + 0x51C)
#define UART_BAUDRATE           REG(UART0_BASE + 0x524)
#define UART_CONFIG             REG(UART0_BASE + 0x56C)
#define BAUD_115200             0x01D7E000UL

#define CLOCK_TASKS_HFCLKSTART  REG(0x40000000UL + 0x000)
#define CLOCK_EVENTS_HFCLKSTARTED REG(0x40000000UL + 0x100)

#define FICR_CODEPAGESIZE       REG(0x10000000UL + 0x010)
#define FICR_CODESIZE           REG(0x10000000UL + 0x014)
#define FICR_DEVICEID0          REG(0x10000000UL + 0x060)
#define FICR_DEVICEID1          REG(0x10000000UL + 0x064)
#define UICR_CLENR0             REG(0x10001000UL + 0x000)
#define UICR_RBPCONF            REG(0x10001000UL + 0x004)
#define UICR_BOOTLOADERADDR     REG(0x10001000UL + 0x014)

#define WDT_RUNSTATUS           REG(0x40010000UL + 0x400)
#define WDT_RR0                 REG(0x40010000UL + 0x600)
#define WDT_RELOAD_KEY          0x6E524635UL

/* Recovered from the stock firmware (uart_init @0x0001FDB4) */
#define PIN_BUS_A               15
#define PIN_BUS_B               20

/* Ninebot bus addressing */
#define ADDR_DASH               0x21
#define ADDR_PC                 0x3F
#define CMD_DUMP_INFO           0x70   /**< reply: device/flash/protection summary */
#define CMD_DUMP_DATA           0x71   /**< reply: 64 bytes of flash + its address */
#define CHUNK                   64U

/* The shared startup.s vectors SysTick; this app polls instead, so it is just a stub. */
void SysTick_Handler(void);
void SysTick_Handler(void) { }

/* ── UART (half-duplex, direction swapped like the stock firmware) ─────────── */

static uint8_t s_tx_pin = 0xFF;

/** @brief Point UART0 at a TX/RX pair; skipped when already correct. @sideeffects */
static void uart_dir(uint8_t tx, uint8_t rx)
{
    if (s_tx_pin == tx) {
        return;
    }
    UART_ENABLE = 0;
    GPIO_PIN_CNF(tx) = 3U;      /* output, disconnect input */
    GPIO_PIN_CNF(rx) = 4U;      /* input, connected, pull-down */
    UART_PSELTXD = tx;
    UART_PSELRXD = rx;
    UART_BAUDRATE = BAUD_115200;
    UART_CONFIG = 0;
    UART_ENABLE = 4U;
    UART_TASKS_STARTTX = 1;
    UART_TASKS_STARTRX = 1;
    UART_EVENTS_RXDRDY = 0;
    s_tx_pin = tx;
}

/** @brief Blocking byte transmit. @sideeffects */
static void tx_byte(uint8_t b)
{
    UART_EVENTS_TXDRDY = 0;
    UART_TXD = b;
    while (UART_EVENTS_TXDRDY == 0U) { }
    UART_EVENTS_TXDRDY = 0;
}

/** @brief Non-blocking receive. @return 1 when a byte was read. */
static int rx_byte(uint8_t *out)
{
    if (UART_EVENTS_RXDRDY == 0U) {
        return 0;
    }
    UART_EVENTS_RXDRDY = 0;
    *out = (uint8_t)UART_RXD;
    return 1;
}

/** @brief Feed the watchdog if the previous firmware left it running. @sideeffects */
static void wdt_feed(void)
{
    if (WDT_RUNSTATUS) {
        WDT_RR0 = WDT_RELOAD_KEY;
    }
}

/* ── Ninebot framing ──────────────────────────────────────────────────────── */

/**
 * @brief Send one `5A A5` frame. LEN counts payload only; CK = (~sum(LEN..payload)) & 0xFFFF LE.
 * @sideeffects drives the bus, then hands the line back to the receiver
 */
static void send_frame(uint8_t cmd, uint8_t arg, const uint8_t *payload, uint8_t len)
{
    uint32_t sum = 0;
    uint8_t i;
    const uint8_t hdr[4] = { ADDR_DASH, ADDR_PC, cmd, arg };

    uart_dir(PIN_BUS_A, PIN_BUS_B);         /* take the line */

    tx_byte(0x5A);
    tx_byte(0xA5);
    tx_byte(len);
    sum += len;
    for (i = 0; i < 4U; i++) {
        tx_byte(hdr[i]);
        sum += hdr[i];
    }
    for (i = 0; i < len; i++) {
        tx_byte(payload[i]);
        sum += payload[i];
    }
    {
        const uint16_t ck = (uint16_t)((sum & 0xFFFFU) ^ 0xFFFFU);
        tx_byte((uint8_t)(ck & 0xFFU));
        tx_byte((uint8_t)(ck >> 8));
    }

    uart_dir(PIN_BUS_B, PIN_BUS_A);         /* release it */
}

/* ── Readable-range policy ────────────────────────────────────────────────── */

/** @return 1 when code region 0 is readback protected (reading it would hard fault). */
static int region0_protected(void)
{
    const uint32_t rbp = UICR_RBPCONF;
    if (rbp == 0xFFFFFFFFU) {
        return 0;                            /* UICR unprogrammed -> no protection */
    }
    return (((rbp >> 8) & 0xFFU) != 0xFFU);  /* PR0 != 0xFF -> protected */
}

/** @return length of code region 0, or 0 when CLENR0 is unprogrammed. */
static uint32_t clenr0(void)
{
    const uint32_t v = UICR_CLENR0;
    return (v == 0xFFFFFFFFU) ? 0U : v;
}

/**
 * @brief Is @p addr safe for this app (region 1) to read?
 *
 * The vector table (0x0..0x80) is never protected by PR0, so it is always allowed.
 */
static int readable(uint32_t addr)
{
    if (!region0_protected()) {
        return 1;
    }
    if (addr < 0x80U) {
        return 1;                            /* vector table is exempt */
    }
    return (addr >= clenr0());               /* only region 1 */
}

/* ── Main ─────────────────────────────────────────────────────────────────── */

/** @brief Announce ourselves: ids, flash geometry, protection, key UICR values. @sideeffects */
static void send_info(void)
{
    uint8_t p[24];
    const uint32_t page = FICR_CODEPAGESIZE;
    const uint32_t size = page * FICR_CODESIZE;
    const uint32_t vals[6] = {
        FICR_DEVICEID0, FICR_DEVICEID1, size, clenr0(),
        UICR_BOOTLOADERADDR, UICR_RBPCONF
    };
    uint32_t i;
    for (i = 0; i < 6U; i++) {
        p[i * 4U + 0U] = (uint8_t)(vals[i] & 0xFFU);
        p[i * 4U + 1U] = (uint8_t)((vals[i] >> 8) & 0xFFU);
        p[i * 4U + 2U] = (uint8_t)((vals[i] >> 16) & 0xFFU);
        p[i * 4U + 3U] = (uint8_t)((vals[i] >> 24) & 0xFFU);
    }
    send_frame(CMD_DUMP_INFO, region0_protected() ? 1U : 0U, p, (uint8_t)sizeof(p));
}

int main(void)
{
    uint32_t addr;
    uint32_t total;

    CLOCK_TASKS_HFCLKSTART = 1;
    while (CLOCK_EVENTS_HFCLKSTARTED == 0U) { }
    CLOCK_EVENTS_HFCLKSTARTED = 0;

    s_tx_pin = 0xFF;
    uart_dir(PIN_BUS_B, PIN_BUS_A);          /* start listening */
    wdt_feed();

    total = FICR_CODEPAGESIZE * FICR_CODESIZE;
    if (total == 0U || total > 0x40000U) {
        total = 0x40000U;                    /* fall back to 256 KB */
    }

    for (;;) {
        /* Announce, then stream the whole flash. Repeat forever so the PC can attach at any
         * time and simply catch the next pass — no command protocol needed. */
        send_info();

        for (addr = 0; addr < total; addr += CHUNK) {
            uint8_t p[4 + CHUNK];
            uint32_t i;
            uint8_t arg = 0;

            p[0] = (uint8_t)(addr & 0xFFU);
            p[1] = (uint8_t)((addr >> 8) & 0xFFU);
            p[2] = (uint8_t)((addr >> 16) & 0xFFU);
            p[3] = (uint8_t)((addr >> 24) & 0xFFU);

            if (readable(addr)) {
                const volatile uint8_t *src = (const volatile uint8_t *)addr;
                for (i = 0; i < CHUNK; i++) {
                    p[4U + i] = src[i];
                }
            } else {
                arg = 1;                     /* protected: report, don't fault */
                for (i = 0; i < CHUNK; i++) {
                    p[4U + i] = 0xFFU;
                }
            }

            send_frame(CMD_DUMP_DATA, arg, p, (uint8_t)(4U + CHUNK));
            wdt_feed();

            {   /* drain anything the PC sent; we accept no commands, this just avoids overrun */
                uint8_t junk;
                while (rx_byte(&junk)) { }
            }
        }
    }
}
