#!/usr/bin/env python3
"""
generate_keys.py — Generate ECDSA-P256 keypair for bootloader firmware signing.

Outputs:
  - private_key.pem   : PEM-encoded private key (keep secret!)
  - public_key.pem    : PEM-encoded public key
  - public_key.h      : C header with raw public key bytes for bootloader embedding

Usage:
    python generate_keys.py [--output-dir keys/]
"""

import argparse
import os
import sys
from datetime import datetime

from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization


def generate_keypair() -> ec.EllipticCurvePrivateKey:
    """Generate a new ECDSA-P256 (secp256r1) key pair."""
    return ec.generate_private_key(ec.SECP256R1())


def export_private_pem(key: ec.EllipticCurvePrivateKey) -> bytes:
    return key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    )


def export_public_pem(key: ec.EllipticCurvePrivateKey) -> bytes:
    return key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )


def get_raw_public_key(key: ec.EllipticCurvePrivateKey) -> tuple[bytes, bytes]:
    """Return raw (x, y) coordinates as 32-byte big-endian values."""
    pub_numbers = key.public_key().public_numbers()
    x = pub_numbers.x.to_bytes(32, byteorder="big")
    y = pub_numbers.y.to_bytes(32, byteorder="big")
    return x, y


def format_c_array(name: str, data: bytes, items_per_line: int = 12) -> str:
    """Format a byte array as a C uint8_t array initializer."""
    lines = []
    for i in range(0, len(data), items_per_line):
        chunk = data[i : i + items_per_line]
        hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hex_vals},")
    return f"static const uint8_t {name}[] = {{\n" + "\n".join(lines) + "\n};"


def generate_c_header(x: bytes, y: bytes) -> str:
    """Generate C header file with public key for bootloader embedding."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    return f"""\
/**
 * @file public_key.h
 * @brief ECDSA-P256 public key for firmware signature verification.
 *
 * AUTO-GENERATED by generate_keys.py on {timestamp}
 * DO NOT EDIT MANUALLY.
 *
 * This key must be embedded in the bootloader binary.
 * The corresponding private key (private_key.pem) must be kept secret
 * and used only for signing firmware images.
 */

#ifndef PUBLIC_KEY_H
#define PUBLIC_KEY_H

#include <stdint.h>

/**
 * ECDSA-P256 (secp256r1) public key.
 * Uncompressed format: 32 bytes X + 32 bytes Y = 64 bytes total.
 */

/* X coordinate (32 bytes, big-endian) */
{format_c_array("ecdsa_public_key_x", x)}

/* Y coordinate (32 bytes, big-endian) */
{format_c_array("ecdsa_public_key_y", y)}

/**
 * Combined public key in the format expected by ecdsa_verify():
 *   pubkey[0..31]  = X coordinate
 *   pubkey[32..63] = Y coordinate
 */
static const uint8_t ecdsa_public_key[64] = {{
    /* X */
{chr(10).join("    " + ", ".join(f"0x{x[i]:02X}" for i in range(j, min(j + 12, 32))) + "," for j in range(0, 32, 12))}
    /* Y */
{chr(10).join("    " + ", ".join(f"0x{y[i]:02X}" for i in range(j, min(j + 12, 32))) + "," for j in range(0, 32, 12))}
}};

#endif /* PUBLIC_KEY_H */
"""


def main():
    parser = argparse.ArgumentParser(
        description="Generate ECDSA-P256 keypair for bootloader firmware signing."
    )
    parser.add_argument(
        "--output-dir",
        "-o",
        default="keys",
        help="Output directory for key files (default: keys/)",
    )
    args = parser.parse_args()

    out_dir = args.output_dir
    os.makedirs(out_dir, exist_ok=True)

    print("Generating ECDSA-P256 (secp256r1) keypair...")
    key = generate_keypair()

    # Save private key PEM
    priv_path = os.path.join(out_dir, "private_key.pem")
    with open(priv_path, "wb") as f:
        f.write(export_private_pem(key))
    print(f"  Private key: {priv_path}")

    # Save public key PEM
    pub_path = os.path.join(out_dir, "public_key.pem")
    with open(pub_path, "wb") as f:
        f.write(export_public_pem(key))
    print(f"  Public key:  {pub_path}")

    # Save C header
    x, y = get_raw_public_key(key)
    header_path = os.path.join(out_dir, "public_key.h")
    with open(header_path, "w") as f:
        f.write(generate_c_header(x, y))
    print(f"  C header:    {header_path}")

    # Print summary
    print()
    print("Public key (hex):")
    print(f"  X: {x.hex()}")
    print(f"  Y: {y.hex()}")
    print()
    print("IMPORTANT:")
    print(f"  - Keep {priv_path} SECRET — it signs firmware images")
    print(f"  - Copy {header_path} into your bootloader include/ directory")
    print(f"  - Rebuild the bootloader after updating the public key")


if __name__ == "__main__":
    main()
