#!/usr/bin/env python3
"""Compute STM32F103 IWDG prescaler/reload for a target watchdog timeout.

Single source of truth for the dashboard firmware's **5000 ms hard watchdog**
(Req 16). Mirrors `ninebot::iwdg_params()` in
`firmware/decompiled/common/include/watchdog_supervisor.h` exactly, so the
firmware and this tool can never disagree.

The IWDG runs from the LSI (~40 kHz, spec'd 30-60 kHz):

    timeout = (4 << PR) * (RLR + 1) / f_LSI       PR in 0..6, RLR in 0..4095

Examples
--------
    python tools/analysis/iwdg_config.py                 # 5000 ms @ 40 kHz
    python tools/analysis/iwdg_config.py --timeout-ms 2000
    python tools/analysis/iwdg_config.py --emit-header    # C snippet
"""
from __future__ import annotations
import argparse
import sys

PR_DIVIDERS = [4, 8, 16, 32, 64, 128, 256]   # 4 << PR, PR = 0..6


def iwdg_params(timeout_ms: int, lsi_hz: int = 40000) -> dict:
    """Smallest-prescaler PR/RLR realising `timeout_ms`. Matches the C++ impl."""
    for pr, presc in enumerate(PR_DIVIDERS):
        ticks = timeout_ms * lsi_hz // 1000 // presc
        if 1 <= ticks <= 4096:
            rlr = ticks - 1
            actual_ms = presc * (rlr + 1) * 1000 / lsi_hz
            return {"pr": pr, "prescaler": presc, "rlr": rlr,
                    "actual_ms": actual_ms, "lsi_hz": lsi_hz}
    # Fall back to the maximum period (/256, reload 4095).
    presc, rlr = 256, 4095
    return {"pr": 6, "prescaler": presc, "rlr": rlr,
            "actual_ms": presc * (rlr + 1) * 1000 / lsi_hz, "lsi_hz": lsi_hz}


def _emit_header(p: dict, timeout_ms: int) -> str:
    return (
        "/* Generated by tools/analysis/iwdg_config.py - do not hand-edit. */\n"
        f"#define DASH_IWDG_TIMEOUT_MS {timeout_ms}u\n"
        f"#define DASH_IWDG_PR  {p['pr']}u   /* prescaler /{p['prescaler']} */\n"
        f"#define DASH_IWDG_RLR {p['rlr']}u  /* reload */\n"
    )


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--timeout-ms", type=int, default=5000,
                    help="target timeout in ms (default: 5000 — the Req-16 hard requirement)")
    ap.add_argument("--lsi-hz", type=int, default=40000,
                    help="LSI nominal frequency (default: 40000)")
    ap.add_argument("--emit-header", action="store_true",
                    help="print a C header snippet instead of the report")
    args = ap.parse_args(argv)

    p = iwdg_params(args.timeout_ms, args.lsi_hz)

    if args.emit_header:
        print(_emit_header(p, args.timeout_ms))
        return 0

    # LSI spread → real timeout window (30-60 kHz per the datasheet).
    lo = p["prescaler"] * (p["rlr"] + 1) * 1000 / 60000
    hi = p["prescaler"] * (p["rlr"] + 1) * 1000 / 30000

    print("STM32F103 IWDG configuration")
    print("============================")
    print(f"  target timeout : {args.timeout_ms} ms")
    print(f"  LSI (nominal)  : {args.lsi_hz} Hz")
    print(f"  IWDG_PR        : {p['pr']}  (prescaler /{p['prescaler']})")
    print(f"  IWDG_RLR       : {p['rlr']}")
    print(f"  actual @nominal: {p['actual_ms']:.1f} ms")
    print(f"  actual @30-60k : {lo:.0f}..{hi:.0f} ms  (LSI tolerance)")
    err = abs(p["actual_ms"] - args.timeout_ms) / args.timeout_ms * 100
    print(f"  nominal error  : {err:.2f} %")

    # Sanity gate for the firmware's hard requirement.
    if not (1 <= p["rlr"] <= 4095) or err > 5.0:
        print("ERROR: target not realisable within 5% — pick another timeout.",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
